name: Artifact Demo

on: [push]

jobs:
  create_file:
    runs-on: ubuntu-latest
    steps:

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-demo-artifact
          path: demo.txt

  read_file:
    runs-on: ubuntu-latest
    needs: create_file
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-demo-artifact

      - name: Read content
        run: cat demo.txt
