name: learn

on: [push]

jobs:
  build: 
   runs-on: ubuntu-latest
   
   steps:
    - name: checkout out
      uses: actions/checkout@v4
      
    - name: Echo the commect
      run: echo "Hello.world"
   
   

