name: node js tests
on:
   push:
    branches:
      - main
   workflow_dispatch:

jobs:
  test:
     runs-on: ubuntu-latest
     steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
         node-version: 18

      - name: Install dependency
        run: npm install

      - name: Runs test
        run: npm test
  deploy:
     needs: test   # 👈 Only runs if test job passes
     runs-on: ubuntu-latest
     steps:
      - name: Simulate deployment
        run: echo "Deploying application..."