name: test secret

on:
    push:
        branch: [main]

jobs: 
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: echo secret is
        run: echo "The secret is $NEW_SECRET"
        env:
            NEW_SECRET: ${{secrets.NEW_SECRET}}
